### ISSUE TITLE
Bug in Level Pool Discharge Formulation

### ISSUE THREAD

**Issue by hellkite500** [NCAR/wrf_hydro_nwm_public#133]
Based on the WRF-Hydro v5 Technical Report page 37 [https://ral.ucar.edu/sites/default/files/public/WRF-HydroV5TechnicalDescription.pdf](url) the level pool discharge is given by the equation Qw(t) = C_w * L*h^(3/2).  However in 

[module_channel_routing:130](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L130)
[module_channel_routing:162](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L162])
[module_channel_routing:194](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L194])
[module_channel_routing:228](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L228])

The equation is using a power of 2/3

## Possible Solution
Change above references to use the power 3./2.

## Your Environment

* Version of the code used: master as of August 10, 2018 [https://github.com/NCAR/wrf_hydro_nwm_public/commits/867c866269b00c38f7c80721ea658fb7c60a6b0a/](url)

Credit Mehdi Rezaeianzadehfor finding this discrepancy, I just submitted the issue.

**Comment by hellkite500** [comment]
I would have submitted the patch, but I wasn't entirely sure why this was this way and figured I would open an issue to discuss it if needed.

**Comment by jmills-ncar** [comment]
We are working on this issue and investigating the impacts
