### ISSUE TITLE
Another (possible) bug in Level Pool Discharge Formulation 

### ISSUE THREAD

**Issue by mehdire61** [NCAR/wrf_hydro_nwm_public#137]
This could be either a missing explanation from document or a bug in the code. 

Based on page 37 of WRF-Hydro V5 Technical Description: "Presently, lake/reservoir object is assumed to have vertical side walls, such that the surface area is always constant.", the "sap" variable must be constant. However, in

[module_channel_routing:134](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L134)

[module_channel_routing:166](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L166)

[module_channel_routing:198](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L198)

[module_channel_routing:232](https://github.com/NCAR/wrf_hydro_nwm_public/blob/867c866269b00c38f7c80721ea658fb7c60a6b0a/trunk/NDHMS/Routing/module_channel_routing.F#L232)

there is an increase in the surface water area. A possibility is that you have considered an extended area above the weir height!
Hope I haven't missed any point here. 

By the way, the method is actually a third-order "Runge-Kutta" for solving continuity equation, not a level pool routing. We may need to consider renaming it. 

## Possible Solution
Use "sap = ar * 1.0E6" instead.

## Your Environment
Version of the code used: master

**Comment by aubreyd** [comment]
Good catch(es), Mehdi! This is corrected now via PR161. We might consider a different area/volume relationship in the future.
https://github.com/NCAR/wrf_hydro_nwm_public/pull/161

**Comment by mehdire61** [comment]
Thanks Aubrey and all for modifying the code.
