### ISSUE TITLE
Channel-only issues

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#147]
Some problems are seen for channel-only not matching the full model and not restarting. 
The behavoir is generally worse under intel, though we are now seeing some difference under gnu. 

Example under Gnu: #142

Going to work on solving these when v2.0 is calmed down (channel-only is not a deliverable).

**Comment by jmccreight** [comment]
Also, under long-range, there's an odd single feature id which is different. (#142)

**Comment by jmills-ncar** [comment]
Channel only now matches full, closing
