### ISSUE TITLE
Bug in Channel Routing module 

### ISSUE THREAD

**Issue by mehdire61** [NCAR/wrf_hydro_nwm_public#149]
There is a redundant call to updateLake_grid for "QLLAKE".
Module channel routing:
[module_channel_routing:1396](https://github.com/NCAR/wrf_hydro_nwm_public/blob/d24469af63586323f7a8d6b2359b718adb732756/trunk/NDHMS/Routing/module_channel_routing.F#L1396)
is exactly the same as:
[module_channel_routing:1393](https://github.com/NCAR/wrf_hydro_nwm_public/blob/d24469af63586323f7a8d6b2359b718adb732756/trunk/NDHMS/Routing/module_channel_routing.F#L1393)

## Possible Solution
change 
[module_channel_routing:1396](https://github.com/NCAR/wrf_hydro_nwm_public/blob/d24469af63586323f7a8d6b2359b718adb732756/trunk/NDHMS/Routing/module_channel_routing.F#L1396)
to:
call updateLake_grid(**QLAKEI**, nlakes,lake_index)

## Your Environment
Version of the code used: master

**Comment by mehdire61** [comment]
@laurareads @aubreyd 
Sorry to bother you again on this. Did you find any chance to check and (if needed) fix this typo/bug?

**Comment by mehdire61** [comment]
Thanks @aubreyd. You're right.

**Comment by aubreyd** [comment]
Well that being said, we will happily take bug reports on ALL configuration options. This may actually fix another issue we have flagged, so this is extremely helpful - thanks, and keep 'em coming!

**Comment by kafitzgerald** [comment]
Addressed in PR #205
