### ISSUE TITLE
Problem with symlink artifact produced by compile_offline_NoahMP.sh

### ISSUE THREAD

**Issue by tjmills** [NCAR/wrf_hydro_nwm_public#17]
compile_offline_NoahMP.sh produces two symlinks in the `trunk/NDHMS` source directory when run: `LandModel` and `LandModel_cpl`.

If the directory is copied without careful attention to these symlinks, they are copy as the target folders. The compile_offline_NoahMP.sh script attempts to delete these files when re-run, but if they exist as directories the script fails.

This may affect compile_offline_Noah.sh as well.

**FIX**

https://github.com/NCAR/wrf_hydro_nwm_public/blob/master/trunk/NDHMS/compile_offline_NoahMP.sh#L39

should be changed to `rm -rf LandModel LandModel_cpl`

**ADDITIONAL ISSUES**
Under no circumstances should artifacts be produced in the source directory. This issue is only one example of the dangers of polluting the source directory with artifacts. A new issue will be opened to address this

**Comment by rcabell** [comment]
For artifact-free, the CMake build systems allows out-of-tree builds.

**Comment by rcabell** [comment]
Closing due to corner-case, lack of recent activity, and upcoming focus on CMake
