### ISSUE TITLE
Prevent pollution of trunk/NDHMS directory with compile artifacts

### ISSUE THREAD

**Issue by tjmills** [NCAR/wrf_hydro_nwm_public#18]
See #17 for an example of the danger of polluting the source directory with artifacts.

All artifacts should be placed in the `Run` directory or cleaned up on compile script exit

**Comment by rcabell** [comment]
For artifact-free builds, the CMake build system allows out-of-tree builds. Traditional Auto(make) build systems frequently generate in-tree artifacts (that _should_ be cleaned by `make clean` or `make distclean`).
