### ISSUE TITLE
Change default value for HYDRO_D to 0

### ISSUE THREAD

**Issue by jmills-ncar** [NCAR/wrf_hydro_nwm_public#221]
HYDRO_D=1 can crash some subprocess commands and schedulers that buffer the stdout. This can cause a silent fail of hte model run and is very confusing when it happens. 

I suggest turning HYDRO_D off by default

**Comment by jmccreight** [comment]
what is "default"? this?
https://github.com/NCAR/wrf_hydro_nwm_public/blob/ec5c275007f87dd4b1a774e309ebc8108b8c0041/trunk/NDHMS/template/setEnvar.sh#L9

**Comment by jmccreight** [comment]
🤕

**Comment by jmills-ncar** [comment]
For better or worse, people are interpreting the setEnvars.sh script as 'default' compile options. Either we should change HYDRO_D there, or find a way to better t convey what it is supposed to be.

I strongly lean towards the former

**Comment by jmccreight** [comment]
oops. man, forgot i could just commit... i was intending a PR. Will PR this to master... though there are supposedly conflicts... 

https://github.com/NCAR/wrf_hydro_nwm_public/commit/8203b7a11f3dc800ad09350446720e2e96a4edfa

**Comment by jmccreight** [comment]
#222

**Comment by jmccreight** [comment]
#223 is easy

**Comment by kafitzgerald** [comment]
Addressed in PR #223
