### ISSUE TITLE
duplicating MPI communicators

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#232]
https://github.com/NCAR/wrf_hydro_nwm_public/blob/8e1dbc21aca54dcccb6cac68d7c009d3e3a1926d/trunk/NDHMS/MPP/mpp_land.F#L156

The above is how not to do it, should use MPI_COMM_DUP.

**Comment by glennpj** [comment]
Hi,
I am building the coupled model of WRF/WRF-hydro for one of our researchers. I am seeing the following error when trying to run the front_range_CO test case, which perhaps is related to the comment above.
```
*** An error occurred in MPI_Bcast
*** reported by process [47923237289985,1]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_COMM: invalid communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```
I did a quick search in MPI docs and see,

> In particular, no library routine should use MPI_COMM_WORLD as the communicator; instead, a duplicate of a user-specified communicator should always be used. 

https://www.mpich.org/static/docs/latest/www3/MPI_Comm_dup.html

I may be looking at the wrong thing but this was the most promising lead that I found. How would I go about duplicating the communicator?

Thanks.

**Comment by afanfa** [comment]
a quick fix is the following:

` integer :: ierr
call MPI_COMM_DUP(MPI_COMM_WORLD, HYDRO_COMM_WORLD, ierr)
`

assuming that an integer varia

**Comment by glennpj** [comment]
@afanfa Sorry for the delayed response but that seems to have done the trick. I made the change in mpp_land.F and CPL_WRF.F.

Thanks so much.

**Comment by afanfa** [comment]
@glennpj that's great news. @jmccreight I am going to make a pull request to reflect that change on master as well.

**Comment by jmccreight** [comment]
#281
