### ISSUE TITLE
Feature_ids in Lakeout jumble when subsetted NWM domain includes partial lake

### ISSUE THREAD

**Issue by laurareads** [NCAR/wrf_hydro_nwm_public#30]
In the case of a cutout from the NWM domain, the Routelink is cutout to include only the links in the domain.  In some cases, inflows/internal lake links can be included without the outlet link.  This is causing an issue in LAKEOUT files, where the feature_id and other fields are non-sensical.  

## Expected Behavior
The model should crash with a message indicating that the lake outlet link was not found and therefore the level pool routine was unable to finish. 
A check should be added to the subsetting tools to prevent partial lakes from being included in the domain. 

##Settings
-UDMP = 1 with a domain extracted using the current NWM subsetting tools.  
-Lakes on.  outlake=1.

**Comment by rcabell** [comment]
Fixed in `wrf_hydro_subsetting` so closing here
