### ISSUE TITLE
PGI build broken with d0444897 

### ISSUE THREAD

**Issue by barlage** [NCAR/wrf_hydro_nwm_public#313]
## Current Behavior
Code (master: 6170c18) is not compiling with PGI 

## Possible Solution
This seems to be from commit d0444897. PGI does not like the syntax of "error stop", change to "stop" will fix.

## Your Environment
* Version of the code used: master (6170c18)
* Operating System and version: Linux
* Compiler and version: PGI 15.1

**Comment by kafitzgerald** [comment]
It looks like support for this wasn't added in PGI until [version 19.1](https://www.pgroup.com/resources/docs/19.1/openpower/pgi-release-notes/index.htm).  Although it was in the [Fortran 2008 standards](http://fortranwiki.org/fortran/show/Fortran+2008) 🤷‍♀.

**Comment by rcabell** [comment]
There's a `hydro_stop()` subroutine in `module_HYDRO_drv.F`; this could (should?) be used instead and have conditional compilation to call the highest-supported intrinsic per compiler/version

**Comment by barlage** [comment]
I've been using PGI 15.1 with the current master (61695aa) and this issue seems to be resolved, so closing issue.
