### ISSUE TITLE
Build .*F > *.f fails on osx native (non-case sensitive) file systems.

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#32]
Legacy OS X filesystems are case insensitive. (Though there appears to be a case sensitive option with APFS now). Because we preprocess *F files to *f files, we can not compile on OS X filesystems (including using docker on a mounted OS X directory). 

If change this convention to something that's not at odds with case-insensitive files systems, the model becomes much more usable via docker. 

Having used the model extensively in docker on my desktop and laptops, this would be a tremendous benefit.

There are two work arounds: 
1) in docker, copy the mounted repo to a non-mounted directory inside docker. Compile. 
2) Put the code on a case-sensitive external drive and mount this into docker.

**Comment by donaldwj** [comment]
Any reason not to just change to preprocessing and compiling in one step. Both gfortran and ifort can process C macros in the file they are compiling. A separate preprocessing step is not needed. Just include -cpp in the compile flags and set any -D[name] macros when compiling

**Comment by jmccreight** [comment]
Nice! I will try that. I was unawares

**Comment by donaldwj** [comment]
The relevant documentation for gfortran is here
https://gcc.gnu.org/onlinedocs/gfortran/Preprocessing-Options.html

and for ifort is here
https://software.intel.com/en-us/node/680210

Apparently the flag to force preprocessing with ifort is -fpp.  But both ifort and gfortran automatically run the preprocessor on .F files unless instructed not too. On a case insensitive filesystem the forcing flag (-cpp or -fpp) may be needed.

**Comment by kafitzgerald** [comment]
Addressed with PR#324
