### ISSUE TITLE
Eliminate 2-step preprocess/compile build mechanism

### ISSUE THREAD

**Issue by rcabell** [NCAR/wrf_hydro_nwm_public#323]
The 2-step preprocess-then-compile method currently in use has a variety of downsides, including:

- creating a lot of temporary files that can be left behind if a build fails, as well as preventing compilation on case-insensitive filesystems (such as are used by default on macOS) where the temporary preprocessed files overwrite the original source files due to having the same name other than a case-inverted extension. 

- displaying incorrect line numbers when compiler errors occur, due to the line numbers being that of the preprocessed file and not the original version-controlled file

## Current Behavior
Currently, all of the Makefiles that deal with preprocessor-annotated source use a `CPP` variable defined in the `macros.*` templates to run the preprocessor before compilation, resulting in two source files. The Makefiles then attempt to clean up the temporaries, but this can fail if the compile step fails.

## Possible Solution
All modern Fortran compilers can internally preprocess source files (or handle calling out to the system preprocessor), making the extra step unnecessary. A new flag in the `macros.*` templates called `CPPINVOKE` would encapsulate the specific flag(s) necessary for correct preprocessing during the compile step.

**Comment by hellkite500** [comment]
#322 also addresses this.
