### ISSUE TITLE
Filenames need to be syntactically correct 

### ISSUE THREAD

**Issue by tjmills** [NCAR/wrf_hydro_nwm_public#34]
There are a number of files output by the model that are not syntactically correct, primarily the restart files with `:` in the filename. For example, `HYDRO_RST.2011-08-26_00:00_DOMAIN1`.

This is incredibly bad practice as they will be renamed or flat out rejected when passing through any system designed to handle diverse filesystem conventions, which is most modern systems or web servers.

All special characters should be removed and replaced with universally acceptable characters such as `_` or debatably preferred `-`

**Comment by rcabell** [comment]
Only an issue with Windows and Classic MacOS, neither of which are supported platforms, so closing for now. Can revisit if operationally needed.
