### ISSUE TITLE
WRF-HYDRO compilation problem

### ISSUE THREAD

**Issue by cgiannaros** [NCAR/wrf_hydro_nwm_public#340]
Hello,

I would like to mention a problem that I have during the compilation of 
WRF-HYDRO v5.0.3 (WRF version 4.0.2):

I have some errors related to the "wrf_hyrdo" part of compilation referring 
to the "module_NWM_io_dict.f". The first lines of the errors are:

module_NWM_io_dict.f(860): error #6404: This name does not have a type, 
and must have an explicit type.   [NF90_USHORT]
                   case (NF90_USHORT)
------------------------^
module_NWM_io_dict.f(860): error #6601: In a CASE statement, the 
case-value must be a constant expression.   [NF90_USHORT]
                   case (NF90_USHORT)
------------------------^
module_NWM_io_dict.f(860): error #6612: In a CASE statement, the 
case-value must be of type INTEGER, CHARACTER, or LOGICAL. [NF90_USHORT]
                   case (NF90_USHORT)
------------------------^
module_NWM_io_dict.f(860): error #6611: The case-value must be of the 
same type as the case-expr.   [NF90_USHORT]
                   case (NF90_USHORT)

It is quite strange because in the same code (module_NWM_io_dict.f) 
there is no issue about other related variables, such as "NF90_SHORT" 
and "NF90_DOUBLE".

As a result, the compilation do not proceed to the creation of wrf.exe, 
even though ndown.exe, tc.exe and real.exe are created.

Could you please help me solving this problem?

Thank you very much in advance!

**Comment by kafitzgerald** [comment]
It looks like you might have your netCDF libraries built without netCDF4 support enabled.  This is not required for WRF, but is for WRF-Hydro.  You can check using the `nc-config` utility: `nc-config --has-nc4`.

**Comment by cgiannaros** [comment]
Dear Katelyn,
Thanks for the quick response! 
I just checked the "nc-config --has-nc4" command and the output is "yes".

**Comment by kafitzgerald** [comment]
I just saw your help ticket.  Let's iterate on this there (if it is indeed a bug w/ the code I'll reopen this issue).

**Comment by rcabell** [comment]
One more thing to check: did you build/install Fortran 90 support? Check that the output of `nc-config --fflags` is reasonable and that the `netcdf.mod` file is in the NetCDF include file directory.

**Comment by cgiannaros** [comment]
Dear Ryan, 
"nc-config --has-f90" gives me "yes".
"nc-config --fflags" gives me "-g -O2 -I/usr/include". 
netcdf.mod is included in the netcdf include directory.
