### ISSUE TITLE
Issue examining land grid in module_NWM_io_dict.F

### ISSUE THREAD

**Issue by camelstation** [NCAR/wrf_hydro_nwm_public#346]
## Expected Behavior
Lines 1503-1521 of module_NWM_io_dict.F examine the land spatial metadata file (GEOGRID_LDASOUT_Spatial_Metadata.nc) to obtain the number of columns, etc. The metadata file is opened at line 1505 and grid attributes are extracted on the subsequent lines.

## Current Behavior
Line 1505 opens the metadata file and gives it the ncid of "ftnGeo". There are four subsequent lines that examine the attributes of this file (`iret = ....`), followed by it being closed line 1519. 

Two of these `iret = ....` use the ncid "ftnGeo", while the other two use "ftnMeta". As "ftnMeta" has not been defined, the model execution fails with: 

```
"The job is stopped due to the fatal error. 
ERROR: Unable to find x variable in LAND spatial metadata file"
```

## Possible Solution
As this section of code is opening and reading the metadata file, replace all "ftnGeo" with "ftnMeta". Example solution as follows

```
      iret = nf90_open(trim(nlst_rt(1)%land_spatial_meta_flnm),NF90_NOWRITE,ncid=ftnMeta)
      if(iret .ne. 0) then
         call postDiagMsg(diagFlag,'WARNING: Unable to open LAND Spatial Metadata file. Defaulting to missing values.')
         numColLand = -9999
         resLand = -9999
      else
         iret = nf90_inq_dimid(ftnMeta,'x',xDimId)
         call nwmCheck(diagFlag,iret,'ERROR: Unable to find x dimension in LAND spatial Metadata file')
         iret = nf90_inquire_dimension(ftnMeta,xDimId,len=numColLand)
         call nwmCheck(diagFlag,iret,'ERROR: Unable to retrieve number of columns in the LAND spatial metadata file')
         iret = nf90_inq_varid(ftnMeta,'x',xVarId)
         call nwmCheck(diagFlag,iret,'ERROR: CAMPBELL Unable to find x variable in LAND spatial metadata file')
         iret = nf90_get_att(ftnMeta,xVarId,'resolution',resLand) 
         call nwmCheck(diagFlag,iret,'ERROR: Unable to get x resolution in LAND spatial metadata file')
         iret = nf90_close(ftnMeta)
         call nwmCheck(diagFlag,iret,'ERROR: Unable to close the LAND spatial metadata file')
      endif

```

## Steps to Reproduce (for bugs)
1. Compile and run. (Perhaps it's something unique about my geogrid_d0X.nc or GEOGRID_LDASOUT_Spatial_Metadata.nc file?)

## Your Environment
* Version of the code used: v5.1.0-beta2, and also v5.0
* Operating System and version: NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
* Compiler and version: Intel 2016/2017 compilers

**Comment by kafitzgerald** [comment]
It looks like this might actually be an issue with reading from the GEO_FINEGRID_FLNM file and an error message that could use to be updated.  This section of code should be reading from this and the spatial metadata file.  Could you dump the header of your GEO_FINEGRID_FLNM file?  ‘ncdump -h filename’

**Comment by camelstation** [comment]
`ncdump -h Fulldom_hires.nc` 
netcdf Fulldom_hires {
dimensions:
	y = 1752 ;
	x = 1416 ;
variables:
	double y(y) ;
		y:standard_name = "projection_y_coordinate" ;
		y:long_name = "y coordinate of projection" ;
		y:units = "m" ;
		y:_CoordinateAxisType = "GeoY" ;
		y:resolution = 41.666667938232 ;
	double x(x) ;
		x:standard_name = "projection_x_coordinate" ;
		x:long_name = "x coordinate of projection" ;
		x:units = "m" ;
		x:_CoordinateAxisType = "GeoX" ;
		x:resolution = 41.666667938232 ;
	char crs ;
		crs:transform_name = "lambert_conformal_conic" ;
		crs:grid_mapping_name = "lambert_conformal_conic" ;
		crs:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		crs:spatial_ref = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		crs:long_name = "CRS definition" ;
		crs:longitude_of_prime_meridian = 0. ;
		crs:GeoTransform = "-108499.930941 41.6666679382 0 70439.5999798 0 -41.6666679382 " ;
		crs:_CoordinateAxes = "y x" ;
		crs:_CoordinateTransformType = "Projection" ;
		crs:standard_parallel = 44., 44. ;
		crs:longitude_of_central_meridian = -72.636 ;
		crs:latitude_of_projection_origin = 43.308 ;
		crs:false_easting = 0. ;
		crs:false_northing = 0. ;
		crs:earth_radius = 6370000. ;
		crs:semi_major_axis = 6370000. ;
		crs:inverse_flattening = 0. ;
	int CHANNELGRID(y, x) ;
		CHANNELGRID:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		CHANNELGRID:grid_mapping = "crs" ;
	short FLOWDIRECTION(y, x) ;
		FLOWDIRECTION:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		FLOWDIRECTION:grid_mapping = "crs" ;
	int FLOWACC(y, x) ;
		FLOWACC:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		FLOWACC:grid_mapping = "crs" ;
	float TOPOGRAPHY(y, x) ;
		TOPOGRAPHY:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		TOPOGRAPHY:grid_mapping = "crs" ;
	float RETDEPRTFAC(y, x) ;
		RETDEPRTFAC:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		RETDEPRTFAC:grid_mapping = "crs" ;
	float OVROUGHRTFAC(y, x) ;
		OVROUGHRTFAC:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		OVROUGHRTFAC:grid_mapping = "crs" ;
	byte STREAMORDER(y, x) ;
		STREAMORDER:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		STREAMORDER:grid_mapping = "crs" ;
	int frxst_pts(y, x) ;
		frxst_pts:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		frxst_pts:grid_mapping = "crs" ;
	int basn_msk(y, x) ;
		basn_msk:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		basn_msk:grid_mapping = "crs" ;
	int LAKEGRID(y, x) ;
		LAKEGRID:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		LAKEGRID:grid_mapping = "crs" ;
	float landuse(y, x) ;
		landuse:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		landuse:grid_mapping = "crs" ;
	float LKSATFAC(y, x) ;
		LKSATFAC:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		LKSATFAC:grid_mapping = "crs" ;
	float LATITUDE(y, x) ;
		LATITUDE:long_name = "latitude coordinate" ;
		LATITUDE:units = "degrees_north" ;
		LATITUDE:_CoordinateAxisType = "Lat" ;
		LATITUDE:grid_mapping = "crs" ;
		LATITUDE:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		LATITUDE:_CoordinateSystems = "crs" ;
	float LONGITUDE(y, x) ;
		LONGITUDE:long_name = "longitude coordinate" ;
		LONGITUDE:units = "degrees_east" ;
		LONGITUDE:_CoordinateAxisType = "Lon" ;
		LONGITUDE:grid_mapping = "crs" ;
		LONGITUDE:esri_pe_string = "PROJCS[\"Lambert_Conformal_Conic\",GEOGCS[\"GCS_Sphere\",DATUM[\"D_Sphere\",SPHEROID[\"Sphere\",6370000.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-72.636],PARAMETER[\"standard_parallel_1\",44.0],PARAMETER[\"standard_parallel_2\",44.0],PARAMETER[\"latitude_of_origin\",43.308],UNIT[\"Meter\",1.0]];-36716200 -30042900 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" ;
		LONGITUDE:_CoordinateSystems = "crs" ;

// global attributes:
		:Conventions = "CF-1.5" ;
		:GDAL_DataType = "Generic" ;
		:Source_Software = "WRF-Hydro GIS Pre-processor v5 (03/2018)" ;
		:proj4 = "+proj=lcc +units=m +a=6370000.0 +b=6370000.0 +lat_1=44.0 +lat_2=44.0 +lat_0=43.308 +lon_0=-72.636 +x_0=0 +y_0=0 +k_0=1.0 +nadgrids=@null +wktext  +no_defs " ;
		:history = "Created Wed Mar 20 11:25:09 2019" ;
		:processing_notes = "Created: Wed Mar 20 10:09:43 2019" ;
		:geogrid_used = "C:\\Users\\AlvaroBuenoBuoro\\Documents\\ArcGIS\\JP_wrf\\ReviewPourPoints\\geo_em.d04.nc" ;
		:DX = 41.666667938232 ;
		:DY = 41.666667938232 ;
		:MAP_PROJ = 1 ;
		:corner_lats = 43.27856f, 43.93206f, 43.93837f, 43.28481f, 43.27853f, 43.93204f, 43.93839f, 43.28481f, 43.27706f, 43.93357f, 43.93988f, 43.2833f, 43.27704f, 43.93354f, 43.93989f, 43.28331f ;
		:corner_lons = -73.97437f, -73.98911f, -73.25641f, -73.24963f, -73.97644f, -73.99118f, -73.2543f, -73.24759f, -73.97437f, -73.98914f, -73.25641f, -73.24963f, -73.97641f, -73.99121f, -73.25433f, -73.24756f ;
		:TRUELAT1 = 44.f ;
		:TRUELAT2 = 44.f ;
		:STAND_LON = -72.636f ;
		:POLE_LAT = 90.f ;
		:POLE_LON = 0.f ;
		:MOAD_CEN_LAT = 43.30799f ;
		:CEN_LAT = 43.60903f ;
}

**Comment by kafitzgerald** [comment]
It looks like I spoke too soon.  

While the values computed in this section xRes and yRes are not used elsewhere and we don't typically see errors in our testing, it looks like your fix is correct.  Thanks for reporting this.

**Comment by camelstation** [comment]
I'm glad I could help, and thanks for responding so quickly.
