### ISSUE TITLE
colons ':' in date-stamped restart files corrupt git clone on ntfs

### ISSUE THREAD

**Issue by jameshalgren** [NCAR/wrf_hydro_nwm_public#351]
When cloning/checking out on Windows, five files are named so that ntfs cannot support the names, which essentially corrupts the repository.

## Expected Behavior

Cloning the repository on any platform (see 'steps to reproduce' below) should produce a clean repository.

## Current Behavior

Cloning the repository throws five errors and generally produces a repository in a strange half-state of disarray. 

## Possible Solution

Ideas: 
1. Use the same correction to the file name convention apparently applied to other files in the same folders. Could be useful to write a function for simple date handling and apply it across the application. 
1a. Push more of the file i/o to a language with standard date-string libraries.
2. Pickle/shelve/otherwise package the restart files. (disadvantage -- requires multiple layers of python/X/netcdf to read it.)
3. provide simple "sparse checkout" instructions for windows git client. (not a really great idea, since it presumably breaks testing; see [this link](https://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument) and "other information" below. 
4. re-write ntfs to properly handle arbitrary strings in file names.

## Steps to Reproduce (for bugs)

1. from Windows git client ```git clone https://github.com/NCAR/wrf_hydro_nwm_public.git```
2. error message: 

```
error: unable to create file tests/config_file_meta/CONUS/nwm_ana/NWM/RESTART/nudgingLastObs.2018-06-01_00:00:00.nc: Invalid argument
error: unable to create file tests/config_file_meta/CONUS/nwm_long_range/NWM/RESTART/nudgingLastObs.2018-06-01_00:00:00.nc: Invalid argument
error: unable to create file tests/config_file_meta/HAWAII/nwm_hi_ana/NWM/RESTART/nudgingLastObs.2018-08-01_00:00:00.nc: Invalid argument
error: unable to create file tests/config_file_meta/croton_NY/nwm_ana/NWM/RESTART/nudgingLastObs.2011-08-26_00:00:00.nc: Invalid argument
error: unable to create file tests/config_file_meta/croton_NY/nwm_long_range/NWM/RESTART/nudgingLastObs.2011-08-26_00:00:00.nc: Invalid argument
```
## Your Environment

* Version of the code used:
Tested on several branches, etc. all show same behavior. 
* Operating System and version:
Windows
* Compiler and version:
N/A
* Other relevant information:
Similar information [here](https://github.com/discogs/discogs_client/issues/37) and [a possible workaround using ```sparsecheckout = true``` in the ```.git/config [core]``` file, with ```.git/info/sparse-checkout``` added with appropriate filters here](https://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument)

**Comment by jmccreight** [comment]
Hello and thanks for the report. 

We have discussed this issue several times in the past, however more in the context of the actual output files (the files you are reporting have the same file names but contain metadata only). While it is something we'd like to do, it is just not a priority for several reasons. 

The larger and more general complication reason is that the colon usage is inherited from WRF, so we dont have total freedom. 

We dont support windows  and it's hard to justify the effort to fix this on a system that we dont support (and likely will not be able to compile the code in any case). If you just want to read the code (an not edit), the github interface is useful.

We have docker containers available for use to circumvent. However, we've also seen difficulty with the colon on host file systems mounted into the docker container.

If you have more compelling arguments that might raise the priority of the issue, please let us know.

**Comment by jmccreight** [comment]
I forgot to ask you to clarify your possible solution. Maybe it's workable, I just dont understand it.

**Comment by jameshalgren** [comment]
Thanks, James, for responding so quickly. I added some detail to the explanation. For now, I will probably use the sparse checkout workaround and will let any of my collaborators who might be using the same system know. We can do our testing on a fairly focused subset of features related to channel routing. The lack of consistent date-string handling is the only reason I can think of to elevate the priority, but I think you are already aware of that in the broader context of development, so I'm not concerned if this floats as a lower priority for a while.

**Comment by jameshalgren** [comment]
###Adding a little to the priority thought: 
Capability to execute wrf-hydro cross platform is a big lift and a low priority. Capability to *develop* wrf-hydro cross platform is a much smaller lift and may increase base of potential contributors. 

###Expanding on possible solution #2 above:
If the test files are packaged in a zip file, there will be no platform incompatibilities for cloning and the test python script can easily check for any zip files and expand them before executing the test.

**Comment by rcabell** [comment]
Will close for now until future need arises.
