### ISSUE TITLE
KDAY in namelist.hrldas is no longer active

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/wrf_hydro_nwm_public#395]
## Expected Behavior
If only KDAY is assigned in the namelist.hrldas file, the WRF-Hydro simulation should run for KDAY days.

## Current Behavior
WRF-Hydro continues to run past KDAY without any error or warning.

It looks like this bug was introduced with PR #357 for the Orchestrator.

## Possible Solution
In config.f90 noah_lsm%kday should be assigned a value from the namelist.

We could also deprecate the KDAY + KHOUR option at some point and just use KHOUR, but let's maybe warn folks 😉 .

## Your Environment
@arezoorn reported this bug while running w/ current master on Cheyenne.

**Comment by rcabell** [comment]
Closed by PR #415
