### ISSUE TITLE
Theia build broken

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#4]
From: Rocky Dunlap

## Expected Behavior

That it configures and compiles under intel. 

## Current Behavior

```
git clone git@github.com:NCAR/wrf_hydro_nwm.git
cd trunk/NDHMS
./configure

Please select from following supported linux compilers
using either the number or key (not case sensitive):

Number    Key  Description
--------------------------------------------
     1    pgi  PGI parallel
     2  gfort  gfortran parallel
     3  ifort  intel parallel (incl. Theia)
     4   luna  ifort parallel (WCOSS Luna)
     0   exit  exit

Enter selection: 3

cp: cannot stat ‘arc/macros.mpp.ifort.theia’: No such file or directory
Configured: ifort on Theia
No compiler selected. Exiting
```

## Possible Solution

```
cd trunk/NDHMS/arc
cp macros.theia macros.mpp.ifort.theia
cd ../
./configure ifort
```

## Steps to Reproduce (for bugs)

See above, specific to theia.

## Your Environment

* Version of the code used:
* Operating System and version:
* Compiler and version:
* Other relevant information:

**Comment by jmccreight** [comment]
I think the proposed solution is desirable for the repo because then the macro file name reflects "mpp" and "ifort" as do the other macro files. If this works I'll commit that change on the public repo.

**Comment by jmccreight** [comment]
just a ping for pings sakes

**Comment by jmccreight** [comment]
another...

**Comment by rsdunlapiv** [comment]
The possible solution above worked for me on Theia.  Do you plan to check in the renamed macro file so that the user does not need to do this step manually?

**Comment by jmccreight** [comment]
Yes! that's the plan.

**Comment by jmccreight** [comment]
and thanks for testing that.
