### ISSUE TITLE
Orchestrator broke reach-routing with UDMP=0

### ISSUE THREAD

**Issue by laurareads** [NCAR/wrf_hydro_nwm_public#414]
## Expected Behavior
The model should produce output when channel_option = 2 and UDMP = 0. 

## Current Behavior
The model finishes successfully but produces no output.

## Possible Solution
Check the orchestrator commits.  I find this issue with the current master: `c99fd7389254594591b2d76aae92f74042e615ab`
If I revert to a commit before the orchestrator merge, I receive the expected behavior. FYI I tested this using commit `d4ea48fcbef924514a2e4b79fb858aad42b155e7`, which is two commits before the orchestrator merge. 

## Steps to Reproduce (for bugs)
1.  Run the Croton testing domain with master (pre/post orchestrator commits referred to above). Set channel_option =2 and UDMP = 0.  Requires reach domain files. 

**Additionally: recommend checking the testing framework, since this was not detected/triggered in the normal travis/CI tests. 

## Your Environment
Docker, master branch of the code.
Compiler: gfort

**Comment by afanfa** [comment]
This may also be related to #395 and fixed by #415

**Comment by laurareads** [comment]
tested afanda's theory and he is correct.  output occurs with khour and not kday using gfort compilers.  will retest when #415 is merged.
