### ISSUE TITLE
NCEP WCOSS compile time option does too much?

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/wrf_hydro_nwm_public#418]
## Current Behavior
The NCEP_WCOSS flag impacts output file metadata in addition to handling other system specific issues making testing and prototyping on other systems difficult.

## Possible Solution
Split the NCEP_WCOSS flag into two.  One for the WCOSS file units, etc. that are specific to the system and one (e.g. NWM_META) for NWM specific IO metadata.

**Comment by rcabell** [comment]
Closed by PR #419
