### ISSUE TITLE
New variable needed in LAKEOUT

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/wrf_hydro_nwm_public#420]
With the ongoing water management development a new output variable is needed in the LAKEOUT files to diagnose where outflow data is coming from.  

Proposed variable + metadata:
```
	int reservoir_type(feature_id) ;
		reservoir_type:long_name = "reservoir_type" ;
		reservoir_type:flag_values = 1, 2, 3, 4 ;
		reservoir_type:flag_meanings = "Level_pool USGS-persistence USACE-persistence RFC-forecasts" ;
```

**Comment by kafitzgerald** [comment]
This has been coded for the sample output files, but still needs to be reviewed and integrated with the water management code.

**Comment by hellkite500** [comment]
Are these files netcdf classic or 64 bit offset files?

**Comment by kafitzgerald** [comment]
This is just a new variable that was desired in the existing LAKEOUT files.  

However, it looks like these are created using the now deprecated `NF90_HDF5` flag.  This should be `NF90_NETCDF4`, but that's probably for another issue.  

Anyway, happy to chat more.

**Comment by rcabell** [comment]
We should update that flag when the PR for this is created. Not sure if it needs a whole separate issue unless it shows up a lot of other places too, then we could fix them all at once.

**Comment by kafitzgerald** [comment]
Fair, it does look like it's relevant for most (if not all) of the NWM output files, but it's contained to a single file at least.  I'll fix it now in that branch before I forget.

**Comment by hellkite500** [comment]
I ask because if we don't need to support those file formats, we could adopt a real enum type: https://www.unidata.ucar.edu/software/netcdf/fortran/docs/f90-user-defined-data-types.html#f90-enum-type-introduction

**Comment by kafitzgerald** [comment]
Ah, true.

Though I think this moves us away from CF compliance.

**Comment by jdmattern-noaa** [comment]
I can work with you @kafitzgerald to integrate this with the water management code after I submit a PR for the Army Corps Persistence today.

**Comment by hellkite500** [comment]
@kafitzgerald Hmm...digging in a little bit, this becomes a very interesting problem with CF/NetCDF development and usage.  Based on these references, it seems the answer is unclear either way:
https://github.com/cf-convention/cf-conventions/issues/192
https://github.com/cf-convention/cf-conventions/issues/191

I'm not really sure we are even using the CF flag concept correctly in this case.  Either way, I agree with the view expressed in 191 that compliance isn't quantitative across the entire product, and using a netcdf feature doesn't invalidate the compliance of the rest of the metadata that is conformant.  Will have to follow the CF issues closely and see how that unfolds.

**Comment by kafitzgerald** [comment]
Sure.  Perhaps the larger concern is broader support for enhanced netCDF4 features.  For instance, ncdf4 in R doesn't seem to support enum types. 

That said, I'm open to ideas and recognize there's room for improvement on IO, metadata, etc.
