### ISSUE TITLE
Build fails using PGI compilers

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/wrf_hydro_nwm_public#460]
This is somewhat of a known issue... but figured it was worth documenting if nothing else as a reminder to remove PGI from the list of supported compilers for next release and perhaps hide that build option in the configure script (it is #1 after all).

## Current Behavior
Builds using PGI compilers fail because of modern Fortran features

## Possible Solution
Remove statements of support for PGI from docs / FAQs

## Steps to Reproduce (for bugs)
Attempt a build w/ env listed below

## Your Environment
* Version of the code used: current master
* Operating System and version: Cheyenne
* Compiler and version: PGI 19.10
* Other relevant information: v5.1.x seems to build fine w/ PGI 19 compilers

**Comment by scrasmussen** [comment]
Fixed and closed by PR #502
