### ISSUE TITLE
NWM v2.0 Reanalysis: valid_range for qBucket and qSfcLatRunoff

### ISSUE THREAD

**Issue by frsalas-noaa** [NCAR/wrf_hydro_nwm_public#474]
valid_range for both qBucket and qSfcLatRunoff set to 0, -2147483648 in CHRTOUT files.

Data pulled from AWS here: https://noaa-nwm-retro-v2.0-pds.s3.amazonaws.com/full_physics/2003/200305011200.CHRTOUT_DOMAIN1.comp

int qBucket(feature_id=2729077);
  :long_name = "Flux from gw bucket";
  :units = "m3 s-1";
  :coordinates = "latitude longitude";
  :grid_mapping = "crs";
  :_FillValue = -999900032; // int
  :missing_value = -999900032; // int
  :scale_factor = 1.0E-5f; // float
  :add_offset = 0.0f; // float
  :valid_range = 0, -2147483648; // int
  :_ChunkSizes = 909693; // int

int qSfcLatRunoff(feature_id=2729077);
  :long_name = "Runoff from terrain routing";
  :units = "m3 s-1";
  :coordinates = "latitude longitude";
  :grid_mapping = "crs";
  :_FillValue = -999900032; // int
  :missing_value = -999900032; // int
  :scale_factor = 1.0E-5f; // float
  :add_offset = 0.0f; // float
  :valid_range = 0, -2147483648; // int
  :_ChunkSizes = 909693; // int

**Comment by rcabell** [comment]
Is this just an issue with the variable metadata or do values reach these range extremes?

**Comment by frsalas-noaa** [comment]
I'm not sure. We used these files to run a channel-only version of the model and the resulting streamflow had values in the millions. I think it's just the metadata and the values themselves are ok.

**Comment by rcabell** [comment]
Ok, we can check too. If it's just the metadata, it should be a (relatively) simple fix.

**Comment by frsalas-noaa** [comment]
What would be a reasonable valid range for those variables?

**Comment by kafitzgerald** [comment]
I'm a little puzzled as to why this is the case.  I just checked some outputs from runs w/ both NWM v2.0 and the latest code both show the following ranges:

```	int qSfcLatRunoff(feature_id) ;
		qSfcLatRunoff:long_name = "Runoff from terrain routing" ;
		qSfcLatRunoff:units = "m3 s-1" ;
		qSfcLatRunoff:coordinates = "latitude longitude" ;
		qSfcLatRunoff:grid_mapping = "crs" ;
		qSfcLatRunoff:_FillValue = -999900000 ;
		qSfcLatRunoff:missing_value = -999900000 ;
		qSfcLatRunoff:scale_factor = 1.e-05f ;
		qSfcLatRunoff:add_offset = 0.f ;
		qSfcLatRunoff:valid_range = 0, 2000000000 ;
	int qBucket(feature_id) ;
		qBucket:long_name = "Flux from gw bucket" ;
		qBucket:units = "m3 s-1" ;
		qBucket:coordinates = "latitude longitude" ;
		qBucket:grid_mapping = "crs" ;
		qBucket:_FillValue = -999900000 ;
		qBucket:missing_value = -999900000 ;
		qBucket:scale_factor = 1.e-05f ;
		qBucket:add_offset = 0.f ;
		qBucket:valid_range = 0, 2000000000 ;
	int qBtmVertRunoff(feature_id) ;
		qBtmVertRunoff:long_name = "Runoff from bottom of soil to bucket" ;
		qBtmVertRunoff:units = "m3" ;
		qBtmVertRunoff:coordinates = "latitude longitude" ;
		qBtmVertRunoff:grid_mapping = "crs" ;
		qBtmVertRunoff:_FillValue = -9999000 ;
		qBtmVertRunoff:missing_value = -9999000 ;
		qBtmVertRunoff:scale_factor = 0.001f ;
		qBtmVertRunoff:add_offset = 0.f ;
		qBtmVertRunoff:valid_range = 0, 20000000 ;
```

It looks like this was the last update to the relevant code was the commit below and that was before NWM v2.0 was released. https://github.com/NCAR/wrf_hydro_nwm_public/commit/21fb06786c6aa12e4a4efe01eaac8cb0fb1627ec

**Comment by rcabell** [comment]
The `-999900032` fill values are particularly odd; my first suspicion is that it's in one of the `io_form_output` routines

**Comment by frsalas-noaa** [comment]
Interesting. The valid_range for the qBtmVertRunoff var on AWS is 0, 500000000 and not 0, 20000000.

**Comment by kafitzgerald** [comment]
The metadata I showed above is from runs with `io_form_outputs = 2`, which is generally what we run for forecasts and retrospectives.  

Regarding the ranges, I'm not sure how these were originally set.  The actual values are generally quite small (at least for qbucket), but I don't have a solid grasp on the ranges offhand.

**Comment by frsalas** [comment]
Just following up on this. Is this an update we can make before running the NWM v2.1 reanalysis?

**Comment by kafitzgerald** [comment]
Are there changes needed beyond what is posted [above](https://github.com/NCAR/wrf_hydro_nwm_public/issues/474#issuecomment-604076103) for output metadata?

I haven't been able to track down why this happened for v2.0, but it's possible something was fixed since then or it was an issue with a specific library we were using at that time.

**Comment by kafitzgerald** [comment]
Ok, I'm going to close this for now then.
