### ISSUE TITLE
Testing: checks for data and metadata should be separated

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#50]
## Expected Behavior

For example, https://github.com/NCAR/wrf_hydro_nwm_public/pull/45

In CI when metadata changes are applied to the CHRTOUT and CHANOBS files, the checks on those files fail and it is ambiguous if the failure is data or metadata. One can not tell and to be sure, should reproduce the test locally. I think it's better to be explicit about this rather than cause all that work

**Comment by kafitzgerald** [comment]
No worries if it’s too much for the log, but on a failure I think it’d be nice to just see the output from nccmp.  This would give us a lot to work with before having to go rerun offline.

**Comment by kafitzgerald** [comment]
Ah, maybe just not for metadata. 

Was hoping for something like this: 
```
DIFFER : NAME OF GLOBAL ATTRIBUTE : model_total_valid_times : GLOBAL ATTRIBUTE DOESN'T EXIST IN NWM/run_reference/201108281400.CHRTOUT_DOMAIN1
DIFFER : VARIABLE "time" IS MISSING ATTRIBUTE WITH NAME "valid_min" IN FILE "NWM/run_reference/201108281400.CHRTOUT_DOMAIN1"
DIFFER : VARIABLE "time" IS MISSING ATTRIBUTE WITH NAME "valid_max" IN FILE "NWM/run_reference/201108281400.CHRTOUT_DOMAIN1"
DIFFER : NUMBER OF ATTRIBUTES : VARIABLE : time : 3 <> 5
```
https://travis-ci.org/NCAR/wrf_hydro_nwm_public/builds/378172024?utm_source=github_status&utm_medium=notification

**Comment by jmills-ncar** [comment]
I have now separated the metadata and data checks but did not closed this issue with the PR as I should have. Closing now
