### ISSUE TITLE
Build fails with gfortran >= 10.0.1

### ISSUE THREAD

**Issue by rcabell** [NCAR/wrf_hydro_nwm_public#523]
## Expected Behavior
WRF-Hydro model should compile with gfortran 10 similarly to gfortran 9 and without errror

## Current Behavior
Errors occur on some files when building with current options:

`Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)`

## Possible Solution
Adding "-fallow-argument-mismatch" to the macros.mpp.gfort file allows the code to build with gfortran-10, but breaks gfortran-9. Using "-std=legacy" allows the code to build with both versions but may have unforeseen side-effects.

**Comment by kafitzgerald** [comment]
Addressed with #524
