### ISSUE TITLE
netcdf_layer.f90 does not compile

### ISSUE THREAD

**Issue by jbensabat** [NCAR/wrf_hydro_nwm_public#596]
Hello 
I am trying to build wrf-hydro with Intel Fortran compiler
File netcdf_layer.f90 does not compile at

 function create_file_parallel(object, path, cmode, initialsize, chunksize, ncid) result(res)
    class(NetCDF_parallel_),intent(in) :: object
    character (len = *), intent(in   ) :: path
    integer,             intent(in   ) :: cmode
    integer, optional,   intent(in   ) :: initialsize
    integer, optional,   intent(inout) :: chunksize
    integer,             intent(  out) :: ncid
    integer                            :: res

    res = 0
   res = nf90_create(path = path, cmode = cmode, ncid = ncid,comm = object%mpi_communicator, info = object%default_info)
    
    
  end function create_file_parallel

the compiler provides the following error messages 

C:\wrf_hydro\wrf_hydro_nwm_public-5.2.0\trunk\NDHMS\IO\netcdf_layer.f90(78): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [COMM]
C:\wrf_hydro\wrf_hydro_nwm_public-5.2.0\trunk\NDHMS\IO\netcdf_layer.f90(78): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [INFO]

thanks for feed-back
best
jac

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of the code used:
* Operating System and version:
* Compiler and version:
* Other relevant information:

**Comment by scrasmussen** [comment]
Addressing in #595
