### ISSUE TITLE
file module_RT.f does not compile 

### ISSUE THREAD

**Issue by jbensabat** [NCAR/wrf_hydro_nwm_public#597]
hello 
module_RT.f does not compile

subroutine getChanDim(did)
  use config_base, only: nlst
  use module_RT_data, only: rt_domain
  implicit none

  integer ixrt,jxrt, ix,jx, did, i,j
  integer, allocatable,dimension(:,:) :: CH_NETLNK, GCH_NETLNK
  !INTEGER, dimension( rt_domain(did)%ixrt,GCH_NETLNK(ixrt,jxrt)) :: GCH_NETLNK, CH_NETLNK

  real :: Vmax

  ix = rt_domain(did)%ix
  jx = rt_domain(did)%jx
  ixrt = rt_domain(did)%ixrt
  jxrt = rt_domain(did)%jxrt

  if(nlst(did)%rtFlag .eq. 0) return

  if(nlst(did)%channel_only       .eq. 1 .or. &
       nlst(did)%channelBucket_only .eq. 1        ) then

   !! Try to avoid some of the 2-d initialization.
   !! if this is successful, it most likely will not work for gridded channel (opt 3)

   if(my_id .eq. io_id) then
      call get_NLINKSL(rt_domain(did)%NLINKSL, nlst(did)%channel_option, nlst(did)%route_link_f)
   end if
   call mpp_land_bcast_int1(rt_domain(did)%NLINKSL)

   if(nlst(did)%channel_option .eq. 1 .or. nlst(did)%channel_option .eq. 2) then
      rt_domain(did)%GNLINKSL = rt_domain(did)%NLINKSL

my_id is not defined and it does not seem to be an imported variable
best
jac

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of the code used:
* Operating System and version:
* Compiler and version:
* Other relevant information:

**Comment by scrasmussen** [comment]
Addressing in #595
