### ISSUE TITLE
NaNs in select reaches under Muskingum-Cunge routing

### ISSUE THREAD

**Issue by aubreyd** [NCAR/wrf_hydro_nwm_public#598]
## Expected Behavior
Real streamflow/velocity/head values in all reaches.

## Current Behavior
Under certain channel parameters, NaNs show up in the streamflow/velocity/head variables. Introduced when compound channel width/roughness are 0 and other less common conditions.

## Possible Solution
Fix divide-by-0s in solver.

## Steps to Reproduce (for bugs)
Seen in nwmv3.0 testing with new channel parameters.

## Your Environment
* Version of the code used: master
* Operating System and version: linux
* Compiler and version: intel18
* Other relevant information:

**Comment by rcabell** [comment]
Closed via #599
