### ISSUE TITLE
No Crash With DTRT in hydro.namelist

### ISSUE THREAD

**Issue by logankarsten** [NCAR/wrf_hydro_nwm_public#634]
Ran the newest version of the code with the old "DTRT" option in the hydro.namelist file. While this was incorrect, the model failed to crash and ran to completion. It failed to write CHRTOUT_DOMAIN and CHRTOUT_GRID files. This may not be high priority, but may need to be addressed with a check for proper namelist variables at some point.

**Comment by rcabell** [comment]
Closing due to DTRT (without CH or TER) no longer being a namelist variable
