### ISSUE TITLE
Multi processes running ./wrf-hydro.exe did not report errors on a single machine but on multiple machines

### ISSUE THREAD

**Issue by v2yield** [NCAR/wrf_hydro_nwm_public#690]
## Expected Behavior

use this command "mpiexec.hydra -print-rank-map -n 4 -machinefile hosts ./wrf_hydro_NoahMP.exe" in one machine in order to run wrf-hydro model in both two machines
## Current Behavior

it reported error:
"NetCDF: Not a valid ID
***** READ_ HRLDAS_ .HDRINFO:  Problems finding dimension 'west_ east '
FATAL ERROR: Model stopped"

## Possible Solution

N/A
## Steps to Reproduce (for bugs)

N/A
## Your Environment

* Version of the code used:
**wrf-hydro v5.2**
* Operating System and version:
**ubuntu:18.04**
* Compiler and version:
**intel mpi 2021.9
zlib-1.2.13
hdf5-1.13.2
netcdf-c-4.9.0
netcdf-fortran-4.6.0
parallel-netcdf-1.12.3
jasper-3.0.3
libpng-1.6.37**
* Other relevant information:
**1.  Data directory for wrf hydro is shared from one machine to another machine by nfs**
**2.  Shared libraries have been added to the environment of both machines**
**3.  hosts file:
               head:2
               node1:2**

**Comment by scrasmussen** [comment]
Hi @v2yield, it looks like that error message is being produced by [this line](https://github.com/NCAR/wrf_hydro_nwm_public/blob/85078a0c1baafcc1edc3cb9fd14f5dce55a67d20/src/Land_models/NoahMP/IO_code/module_hrldas_netcdf_io.F#L384). Could you print the value of the `ierr` returned by the `nf90_open` call just above it, or even better at line 382 in [module_hrldas_netcdf_io.F](https://github.com/NCAR/wrf_hydro_nwm_public/blob/85078a0c1baafcc1edc3cb9fd14f5dce55a67d20/src/Land_models/NoahMP/IO_code/module_hrldas_netcdf_io.F#L382) add the following?
```
call error_handler(ierr, failure="READ_HRLDAS_HDRINFO:  Problems opening wrfinput_flnm")
```

Just want to double check that the first error is the one you are getting and not the opening of the file. Thanks!

**Comment by v2yield** [comment]
wrf_hydro 5.2 version of the module_hrldas_netcdf_io.F file already has
"call error_handler(ierr, failure="READ_HRLDAS_HDRINFO: Problems opening
wrfinput_flnm")"
But this command does not report an error
Have you ever tried to run multiple machines successfully?

Soren Rasmussen ***@***.***> 于2023年5月4日周四 00:39写道：

**Comment by v2yield** [comment]
I'm sorry, I read it as a noah mode file.
I added this line to the module_hrldas_netcdf_io.F file and it reported the
following error
NetCDF: HDF error

 ***** READ_HRLDAS_HDRINFO: Problems opening wrfinput_flnm

FATAL ERROR: Model stopped

Ye W ***@***.***> 于2023年5月5日周五 19:38写道：

**Comment by v2yield** [comment]
I'm sorry, I read it as a noah mode file.
I added this line to the module_hrldas_netcdf_io.F file and it reported the
following error
NetCDF: HDF error

 ***** READ_HRLDAS_HDRINFO: Problems opening wrfinput_flnm

FATAL ERROR: Model stopped

**Comment by scrasmussen** [comment]
> I'm sorry, I read it as a noah mode file.
I added this line to the module_hrldas_netcdf_io.F file and it reported the
following error
NetCDF: HDF error
>
>***** READ_HRLDAS_HDRINFO: Problems opening wrfinput_flnm
>
>FATAL ERROR: Model stopped

> Have you ever tried to run multiple machines successfully?

@v2yield we often run WRF-Hydro across multiple nodes using MPI. To double check I tested using `mpiexec.hydra` and Intel and our machines and everything ran smoothly. You said the host file is
```

**Comment by v2yield** [comment]
Thank you. I finally found out that the nfs file system is out of sync with multiple machines, which caused this error
