### ISSUE TITLE
pytest metafunc parameters and conditional tests

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_nwm_public#81]
This is a testing "bug" or at least "non-feature". 

A consequence of some details of pytest and/or how we are using it means that test questions cannot be conditional to configurations (e.g. NWM, Reach, Gridded). In other words: all test questions are required for all configurations. Though they can be skipped conditionally at test time, all test questions are collected for all configurations at the beginning of pytest execution but subsequently skipped at test time and reported as such. The issue is that it makes testing overly verbose and that the problem is likely to grow so that noise is greater than signal in the test log/output. This is likely to happen soon.

The current case is specifically: For [NWM, Gridded, Reach] configurations the inclusion of new tests for channel-only with NWM results in 4 extra tests questions which should only be run with NWM configuration, but the tests must be included for all configurations in the collection. Currently this boosts the total number of questions collected per configuration from 9 to 13, resulting in 39 collected where as there are only 13+9+9=31 meaningful tests. This is a 20 percent bloat in test reporting due to how things are being done with pytest.

While this is tolerable at the moment, if we begin designing configuration-specific tests it's going to be untenable very quickly.

It's unclear if this is a current short coming of pytest or if we could restructure our tests to avoid this. Understanding this is a first step forward.

**Comment by jmills-ncar** [comment]
I think we can work with this by re-designing how we execute the tests.

I will take a look today but my initial hunch is to get rid of the parameterized tests. This will make it more onerous on the coding side but allow for more control and flexibility. For example, we can create test modules, e.g. `fundamental_questions.py` , and then draw question functinos from those in configuration specific tests.

`test_gridded.py`
```python
from .fundamental_questions import *
from .someotherwuestions import q1, q4, q6

def test_compile_reference(...):
   ...

def test_gridded_speccific_test(...):
   ...
```

There is gonna be some foo-er-y with pytest but I think a design pattern like that might work

**Comment by jmills-ncar** [comment]
We implemented this change and should have closed this issue with the PR but did not. Closing now
